### ISSUE TITLE
SyntaxError: Invalid or unexpected token in nextjs 

### ISSUE THREAD

**Issue by SongWanathong** [ehsankh1370/React-Numeric-Keyboard#1]
hello sir 
I'm trying to use React-Numeric-Keyboard in nextjs and it fails with the message
![image](https://user-images.githubusercontent.com/31090851/207540740-2f88a035-c213-4d69-a483-00f736938b02.png)
i have checked backspace.png and saw that the file was invalid
can you help me fix this issuse?

**Comment by ehsankh1370** [comment]
Hey there,
Can you provide the code you are using in which you are getting this error?

**Comment by SongWanathong** [comment]
here sir i use npm create next-app to setup project and npm install react-numeric-keyboard to try to use NumericKeyboard 
```import Head from 'next/head'
import styles from '../styles/Home.module.css';
import { NumericKeyboard } from 'react-numeric-keyboard';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <NumericKeyboard isOpen={true} onChange={(val)=>{console.log(val)}}  />
        
    
      </main>
    </div>
  )
}
```

**Comment by ehsankh1370** [comment]
This might be the known issue in nextjs. please visit this link:
https://github.com/vercel/next.js/discussions/12410
 @song23284
